language: node_js
node_js:
  - "0.10"
before_install:
  - npm install grunt-cli -g
install: npm install
deploy:
  provider: npm
  email: bb@bftmedia.de
  api_key:
    secure: XbguG88qFeaSOxxUiZLn6lQjI0EWcU9PFDdBw0v2Qo/XX9MlsQYsGkx/piTqmcLUre+5XChvUeumzJxfl6JSd/8MSuqATkOWWakQBjjEmElqzwLARCIY43VvFe6yS7IPyhSw2l/1EXmFJgnzPPhqfT7rTr564uH9mUdIMfwWlXU=
  on:
    tags: true
    repo: b263/grunt-image-jsx
    # Change when this is fixed: https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
